### ISSUE TITLE
Naming convention 

### ISSUE THREAD

**Issue by devmsh** [cleaniquecoders/blueprint-macro#2]
Hi!

Today I was wondering why I repeat using 
```php
$table->unsignedInteger('user_id');
$table->foreign('user_id')->references('id')->on('users');
```

nested of using somthing like
```php
$table->belongsTo('user');
```

Once I google "Laravel blueprint macro" your fresh package appear on the first search results :D 

I like the developed features, and it seems that you still work on the documentation of the available features and macros.

I would like to contribute on this package if you have any further plan, and the first thing I think about is to use the same naming convention from Eloquent to deal with relations as I mention in my previous example. It will be more familiar for the developers to use "belongsTo" both in models and migrations for example.

I'm the first to watch the repo, and I hope to be the first to contribute based on your response and ideas

**Comment by nasrulhazim** [comment]
Hi, 

Ah! that belongsTo idea is a good one! never thought of that! probably you can fork and make contributions on that.

You can use `addForeign` and `referenceOn` macro to have the `belongsTo` macro.
